version: "3.7"

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: super_secret_key
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: superset
      DATABASE_PASSWORD: superset
      DATABASE_DB: superset
      ENABLE_CSV_UPLOAD: "true"
      ENABLE_EXCEL_UPLOAD: "true"
      UPLOAD_FOLDER: /app/superset_home/uploads
    volumes:
      - superset_home:/app/superset_home
      - ./uploads:/app/superset_home/uploads
    depends_on:
      - db
    restart: always
    command: >
      /bin/sh -c "
      pip install pandas openpyxl &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"

  db:
    image: postgres:13
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
  superset_home:
